Portfolio mobile version 2
eng-mohamed-eldeeb/protfolio pull request #3
Opened 2022-01-07 15:12 UTC by eng-mohamed-eldeeb

Create "Works" and "About Myself" sections.

2022-01-07 16:55 UTC, Amrhub requested changes
Hi  @eng-mohamed-eldeeb,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +      <div class="container3">
[ OPTIONAL ] I would recommend using display `grid` on the main container of this section in that case it's `<section class=" works">` just to avoid adding another HTML element where it's not necessary that would keep our code cleaner.
unless you are using it for another purpose I might've missed

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +          <h2 class="LETS connect">LET’S CONNECT</h2>
- [ ] let's make sure to use `h3` since in this section we already have an `h2` tag to follow HTML Semantic rules.
You could also refer to [this video](https://www.youtube.com/watch?v=NexL5_Vdoq8) to help you understand more about it

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +            </div>
- [ ] `Languages`, `Frameworks`, and `Skills` should be inside `li` inside   `ul`, since they represent an un-ordered list for Semantic HTML

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +            </li>
- [ ] let's make sure we use `a` in all of these icons since in the future they will represent a link to your social networks

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +              <i class="far fa-hand-peace"></i>
- [ ]  May you please follow the design in using the same Icons and all of them, we are missing `linked in`, also we are using different icons. 

Your Icons | Figma design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/87689547/148575720-9a40f2fa-ddc6-4ef4-8971-505a0207a368.png) | ![image](https://user-images.githubusercontent.com/87689547/148575800-f2abb0c3-0ebd-4d26-a9eb-633fdb884507.png)

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +              <li class="ppp">html</li>
- [ ] [OPTIONAL] let's make sure we use professional/meaningful class names that help other developers to identify what is the purpose of this class you could [read more](https://stackoverflow.com/questions/2260466/what-is-the-benefit-of-writing-meaningful-css-class-and-id-names) about the advantages in this stack overflow article

2022-01-07 16:55 UTC, Amrhub commented on index.html
> +              <i class="far fa-hand-peace"></i>
- [ ] Please let's make sure we follow Figma design   lets use the same font family in the project as Figma design as you could see difference in the image above

2022-01-07 18:24 UTC, eng-mohamed-eldeeb commented
Can not but Languages, Frameworks, and Skills should be inside "li" inside "ul". Because I get a linter error since they are already inside a ul.

2022-01-07 19:35 UTC, VICTOR-CHUKWU requested changes
Hi @eng-mohamed-eldeeb  👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 19:35 UTC, VICTOR-CHUKWU commented on index.html
> +            </ul>
- [ ] Just as previous reviewer suggested,  `Languages`, `Frameworks`, and `Skills` should be inside li inside ul
   example
```
<ul class="Languages-1">
<li>
<h3>Languages</h3>
 <i class="fas fa-angle-down"></i>
</li>
<li class="language">
     <img src="./img/js.png" alt="" />
     <p>JavaScript</p>
 </li>
</ul>

2022-01-07 19:35 UTC, VICTOR-CHUKWU commented on index.html
> +          </p>
# Optional but Important!
- [ ] [OPTIONAL] Kindly align about me to follow the Figma design
    Your design 👇 
              
![image](https://user-images.githubusercontent.com/66097371/148597054-5c81b14b-cf72-4966-a822-cc836b255d52.png)
  Figma design 👇 
      
![image](https://user-images.githubusercontent.com/66097371/148597194-9624a084-6c6f-4062-ae1b-ade1a22687e0.png)

2022-01-08 12:33 UTC, Deepakdanger approved these changes
Hi @eng-mohamed-eldeeb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 14:09 UTC, merged